server:
 port: 8001 # 服务绑定的端口，不写默认是8080

#开发配置
spring:
 datasource:
  master:
   #基本属性
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.cj.jdbc.Driver
   jdbc-url: jdbc:mysql://127.0.0.1:3306/test_master?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
   username: root
   password: 123456
   connection-timeout: 30000
   idle-timeout: 600000
   max-lifetime: 620000
   maximum-pool-size: 30
   minimum-idle: 5
  second:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.cj.jdbc.Driver
   jdbc-url: jdbc:mysql://127.0.0.1:3306/test_second?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
   username: root
   password: 123456
   connection-timeout: 30000
   idle-timeout: 600000
   max-lifetime: 620000
   maximum-pool-size: 30
   minimum-idle: 5
  #配置rabbitMq 服务器
# rabbitmq:
#  host: 192.168.130.001
#  port: 5672
#  username: admin
#  password: abcd12345
#  #虚拟host 可以不设置,使用server默认host
#  virtual-host: /
#  #消息发送到交换机确认机制,是否确认回调
#  #确认消息已发送到交换机(Exchange)
#  publisher-confirms: true
#  #确认消息已发送到队列(Queue)
#  publisher-returns: true
# redis: # redis配置
#  host: localhost
#  password: 123456
#  port: 8397
#  jedis:
#   pool:
#    max-active: 8
#    max-idle: 8
#    min-idle: 0
# jackson: # 关于jackson的配置
#  default-property-inclusion: non_null
# serialization:
#  write_dates_as_timestamps: true
# cache:
#  redis:
#   time-to-live: 86400s